services:
  agent_two:
    build: .
    container_name: agent_two
    ports:
      - "8081:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: ["python", "agent.py"]
