services:
  router_agent:
    build: .
    container_name: router_agent
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
