services:
  agent_one:
    build: .
    container_name: agent_one
    ports:
      - "8080:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: ["python", "agent.py"]
